# Site Settings
title                    : "rdrn recipes"

collections:
  recipes:
    output: true
    permalink: /r/:slug
  categories:
    output: true
    permalink: /:slug

# Reading Files
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - _recipes/template.md
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  style: compressed
